#!/usr/bin/env groovy
/**
 * NSO-DevOps-in-a-tin-can
 * Author: @ponchotitlan
 *
 * Declarative script of the Jenkins pipeline stages for NSO Use Case testing.
 * The setup of Jenkins and Gitlab-CE is required as per described in the following repository:
 * 
 * https://github.com/ponchotitlan/NSO-DevOps-in-a-tin-can
 */

pipeline {
    agent any
    stages {
       stage('NSO setup') {
        /*
         * Jenkins will pull the NSO Docker image indicated in the yaml configuration file
         * and spin up a container ready to be used for testing
         */
         steps{
            updateGitlabCommitStatus name: 'NSO setup', state: 'pending'
            script{
              def ContainerHandler = load "pipeline_utils/ContainerUtils.Groovy"
              ContainerHandler.spinNSOContainer("cisco-nso-dev:6.0-root","nso6.0")
            }
            updateGitlabCommitStatus name: 'NSO setup', state: 'success'
         }          
       }

       stage('NEDs setup') {
        /*
         * Jenkins will load the required NED files indicated in the yaml configuration
         * file into the previously created NSO container and issue a packages reload.
         * The NEDs must me present in the ${HOME}/nso_cicd_tincan/neds location.
         */
        steps{
          updateGitlabCommitStatus name: 'NEDs setup', state: 'pending'
          script{
            String[] NEDS = ["cisco-ios-cli-6.88"]
            def ContainerHandler = load "pipeline_utils/ContainerUtils.Groovy"
            ContainerHandler.loadNEDs(NEDS,"nso6.0")
          }
          updateGitlabCommitStatus name: 'NEDs setup', state: 'success'
        }
       }       
      
       stage('Workspace cleanup') {
        /*
         * Jenkins will destroy the created NSO container used throughout the process
         */
         steps{
          updateGitlabCommitStatus name: 'Workspace cleanup', state: 'pending'
          echo "TODO: Cleanup"
          // script{
          //   def ContainerHandler = load "pipeline_utils/ContainerUtils.Groovy"
          //   ContainerHandler.destroyNSOContainer("nso6.0")
          // }
          updateGitlabCommitStatus name: 'Workspace cleanup', state: 'success'
         }
       }
    }
 }