# NSO-DevOps-in-a-tin-can
# Author: @ponchotitlan
# 
# Docker-compose file for deploying jenkins

version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 4040:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - $JENKINS_HOME:/var/jenkins_home
      - $INVENTORY:/my_neds
      - /var/run/docker.sock:/var/run/docker.sock