# NSO-DevOps-in-a-tin-can
# Author: @ponchotitlan
# 
# Environment definitions
#
# This is a very basic environment definition of testing and production environments for use on the pipeline execution of this project

##############################################
# Set here the names of the testbed elements #
##############################################
variables:
  STAGING_NSO_VERSION: "6.0"
  STAGING_NSO_DOCKER_IMAGE: "ned/testnso:6.0-root-alfsando"
  STAGING_NETSIM_PREFIX: "netsim-iosxr-dev-"
  STAGING_NETSIM_DOCKER_IMAGE: "ned/netsim-cisco-iosxr-cli-7.43:6.0-root-alfsando"

######################################################################################
# Set here the names of the production elements (simulated by another NSO container) #
######################################################################################
  PRODUCTION_NSO_CONTAINER: "nso-production-6.0"